sudo: false                # explicitly enable sudo 
language: objective-c      # choose your language, here is a sample for oc project
osx_image: beta-xcode6.3   # choose your xcode version

# addons:
#   apt:  # not supported by osx workers
#     packages:
#       - python-pip
#       - python-dev
#       - python-virtualenv

env:
  global:
    # travis encrypt super_secret_password=Io5jboEHGfXc2byuvhOn
    # openssl aes-256-cbc -k "Io5jboEHGfXc2byuvhOn" -in README.md -out README.md.enc
    - secure: H1cRtWKyzGtJEYNUUsxxTB5x/A0Sy7qw5vVh2KWv83eYL5zrsxAvJ52Tmh98xR5U4nc91ZZAtyj5xg9zo/3+FFUTXWma9YApR0c47pNrI5nqshxFqUiwAwFnhJ7FeHW0aEEoDtI7OPE9CIheKzHPk36vl/QBqa1+gJ9fe8Uc8Bw6MjwYnbWPjUmFoyJEALGLoxRRF+Pd4jjF3UEakGCRJipOR92rgDvTfmWaep0nTImtmDQUnaa0ogkJx48EqHCnITT2xGTpWTBfDqN46z8R/zNktUzlNOjRxSzHE5OFlx4KqhL2/CRODXdbmz8jBft+fH9Y/b/6TPJAfZybS2oHaO+34ZmK1QnkTa3JEG3dnpk3tPQSFp6TCCw4wMy5rUbKLnZJAtLvzM8uIwRGVAPOKgob9ArfS3jiDRpqPPG4T3KhBvbvogCJe2RSlr7Hd7xu3F/N8iQZZUOoGymcOoiy5BmGPg6Fblqg3Vn+K2GdvOXCYzC6BrcB63z3TWb1O1SMMVXyoedb9N0OJpNcV+rLkfBm1uw13PVOU9zKgD6DsdUmEBzcKl5Z19qY5HA/Jbc6daYdB1fGmcssitFsQ0y10k7rIqhQ0D54bcpzrPKHIP8DfJCG4ZEEdTWYqYEAlaAmtidfSfix9SGayGIlZE3MhBbVnp4tDHs8t55di2boxLQ=
    # travis-ext
    - TRAVIS_EXT_HOME=$HOME/travis-ext
    - TRAVIS_EXT=$TRAVIS_EXT_HOME/travis-ext.sh
    - TRAVIS_EXT_VERBOSE=true
    # infer
    - PATH="$PATH:$HOME/infer/infer/infer/bin"

before_install:
  # - ./scripts/test_encrypted_file.sh
  # - ./scripts/list_installed_packages.sh 
  # - ./scripts/install_pip.sh
  # - git clone --depth=50 --branch=develop https://github.com/westmisfit/travis-ext.git $TRAVIS_EXT_HOME
  # - ./scripts/install_infer.sh

install:
  - "bundle install --jobs=3 --retry=3 --deployment --path=vendor/bundle && export PATH=$PATH:`pwd`/vendor/bundle/ruby/2.0.0/bin"

script:
  # - infer -- xcodebuild -target testapp-c -configuration Debug -sdk iphonesimulator
  - fastlane staging
  # - xctool -showBuildSettings | egrep '(BUILT_PRODUCTS_DIR)|(CURRENT_ARCH)|(OBJECT_FILE_DIR_normal)|(SRCROOT)|(OBJROOT)' |  egrep -v 'Pods'
  # - xcodebuild -showBuildSettings | egrep '(BUILT_PRODUCTS_DIR)|(CURRENT_ARCH)|(OBJECT_FILE_DIR_normal)|(SRCROOT)|(OBJROOT)' |  egrep -v 'Pods'

after_success:
  # - coveralls

# caching are currently only available for private repositories on travis-ci.com
# and our new container-based infrastructure.
# see http://docs.travis-ci.com/user/caching/
cache:
  directories:
    - vendor/bundle
