sudo: true                 # explicitly enable sudo 
language: objective-c      # choose your language, here is a sample for oc project
osx_image: beta-xcode6.3   # choose your xcode version

before_install:
  - openssl aes-256-cbc -K $encrypted_542e2a05727f_key -iv $encrypted_542e2a05727f_iv
    -in README.md.enc -out test_README.md -d
  - cat README.md
  - cat test_README.md

  - which pip || true
  - which easy_install || true
  - which brew || true
  - which python || true
  - which ruby || true
  - which pod || true
  - which mvn || true
  - which gem || true
  - which rvm || true
  - which bundle || true
  - which xcodebuild || true
